// <auto-generated />
using System;
using Knowz.SelfHosted.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Knowz.SelfHosted.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SelfHostedDbContext))]
    [Migration("20260213204812_AddEntityUpdatedAtAndInboxType")]
    partial class AddEntityUpdatedAtAndInboxType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KnowledgeTags", b =>
                {
                    b.Property<Guid>("KnowledgeItemsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("KnowledgeItemsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("KnowledgeTags");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Knowz.Core.Entities.InboxItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("InboxItems");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Knowledge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("IndexedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIndexed")
                        .HasColumnType("bit");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TopicId");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.HasIndex("TenantId", "FilePath");

                    b.HasIndex("TenantId", "Title");

                    b.HasIndex("TenantId", "Type");

                    b.ToTable("KnowledgeItems");
                });

            modelBuilder.Entity("Knowz.Core.Entities.KnowledgeEvent", b =>
                {
                    b.Property<Guid>("KnowledgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("KnowledgeId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("KnowledgeEvents");
                });

            modelBuilder.Entity("Knowz.Core.Entities.KnowledgeLocation", b =>
                {
                    b.Property<Guid>("KnowledgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("KnowledgeId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("KnowledgeLocations");
                });

            modelBuilder.Entity("Knowz.Core.Entities.KnowledgePerson", b =>
                {
                    b.Property<Guid>("KnowledgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("KnowledgeId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("KnowledgePersons");
                });

            modelBuilder.Entity("Knowz.Core.Entities.KnowledgeVault", b =>
                {
                    b.Property<Guid>("KnowledgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("KnowledgeId", "VaultId");

                    b.HasIndex("TenantId");

                    b.HasIndex("VaultId");

                    b.ToTable("KnowledgeVaults");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Vault", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("ParentVaultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VaultType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentVaultId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Name");

                    b.ToTable("Vaults");
                });

            modelBuilder.Entity("Knowz.Core.Entities.VaultAncestor", b =>
                {
                    b.Property<Guid>("AncestorVaultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DescendantVaultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.HasKey("AncestorVaultId", "DescendantVaultId");

                    b.HasIndex("DescendantVaultId");

                    b.ToTable("VaultAncestors");
                });

            modelBuilder.Entity("KnowledgeTags", b =>
                {
                    b.HasOne("Knowz.Core.Entities.Knowledge", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Knowz.Core.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Knowz.Core.Entities.Knowledge", b =>
                {
                    b.HasOne("Knowz.Core.Entities.Topic", "Topic")
                        .WithMany("KnowledgeItems")
                        .HasForeignKey("TopicId");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Knowz.Core.Entities.KnowledgeEvent", b =>
                {
                    b.HasOne("Knowz.Core.Entities.Event", "Event")
                        .WithMany("KnowledgeEvents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Knowz.Core.Entities.Knowledge", "Knowledge")
                        .WithMany("KnowledgeEvents")
                        .HasForeignKey("KnowledgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Knowledge");
                });

            modelBuilder.Entity("Knowz.Core.Entities.KnowledgeLocation", b =>
                {
                    b.HasOne("Knowz.Core.Entities.Knowledge", "Knowledge")
                        .WithMany("KnowledgeLocations")
                        .HasForeignKey("KnowledgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Knowz.Core.Entities.Location", "Location")
                        .WithMany("KnowledgeLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Knowledge");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Knowz.Core.Entities.KnowledgePerson", b =>
                {
                    b.HasOne("Knowz.Core.Entities.Knowledge", "Knowledge")
                        .WithMany("KnowledgePersons")
                        .HasForeignKey("KnowledgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Knowz.Core.Entities.Person", "Person")
                        .WithMany("KnowledgePersons")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Knowledge");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Knowz.Core.Entities.KnowledgeVault", b =>
                {
                    b.HasOne("Knowz.Core.Entities.Knowledge", "Knowledge")
                        .WithMany("KnowledgeVaults")
                        .HasForeignKey("KnowledgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Knowz.Core.Entities.Vault", "Vault")
                        .WithMany("KnowledgeVaults")
                        .HasForeignKey("VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Knowledge");

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Vault", b =>
                {
                    b.HasOne("Knowz.Core.Entities.Vault", "ParentVault")
                        .WithMany("Children")
                        .HasForeignKey("ParentVaultId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentVault");
                });

            modelBuilder.Entity("Knowz.Core.Entities.VaultAncestor", b =>
                {
                    b.HasOne("Knowz.Core.Entities.Vault", "AncestorVault")
                        .WithMany("Descendants")
                        .HasForeignKey("AncestorVaultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Knowz.Core.Entities.Vault", "DescendantVault")
                        .WithMany("Ancestors")
                        .HasForeignKey("DescendantVaultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AncestorVault");

                    b.Navigation("DescendantVault");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Event", b =>
                {
                    b.Navigation("KnowledgeEvents");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Knowledge", b =>
                {
                    b.Navigation("KnowledgeEvents");

                    b.Navigation("KnowledgeLocations");

                    b.Navigation("KnowledgePersons");

                    b.Navigation("KnowledgeVaults");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Location", b =>
                {
                    b.Navigation("KnowledgeLocations");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Person", b =>
                {
                    b.Navigation("KnowledgePersons");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Topic", b =>
                {
                    b.Navigation("KnowledgeItems");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Vault", b =>
                {
                    b.Navigation("Ancestors");

                    b.Navigation("Children");

                    b.Navigation("Descendants");

                    b.Navigation("KnowledgeVaults");
                });
#pragma warning restore 612, 618
        }
    }
}
